server:
    port: 8080
    address: localhost

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/account
        username: root
        password: 123456
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: roy
        password: 123456
        virtualhost: /
logging:
    level:
        com.roy: DEBUG